[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "kl_mmt"
version = "0.1.0"
description = "KL fitting toolkit"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["klm*", "core*", "summary*"]
exclude = ["archived*", "diagnostics*", "visualization*"]
